// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UIGenerator.Templates
{
    using System.Linq;
    using Focus.Common.Attributes;
    using System.ComponentModel.DataAnnotations;
    using System.Reflection;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ListHtmlTemplate : ListHtmlTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<breadcrumb [itemId]=\"");
            
            #line 9 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.TypeId));
            
            #line default
            #line hidden
            this.Write("\"></breadcrumb>\r\n<section class=\"widget\" widget>\r\n  <div class=\"widget-body\">\r\n  " +
                    "  <div class=\"mt\">\r\n      <div class=\"width-200 float-xs-left\">\r\n        <a clas" +
                    "s=\"btn btn-secondary width-100 mb-xs\" role=\"button\" [routerLink]=\"[\'/app/");
            
            #line 14 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(moduleName));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 14 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name.ToLower(new System.Globalization.CultureInfo("en-EN", false))));
            
            #line default
            #line hidden
            this.Write(@"']"">
          <i class=""glyphicon glyphicon-plus text-success""></i>
          Add
        </a>
      </div>
      <div class=""width-200 float-xs-right"">
        <div class=""input-group input-group-sm input-group-transparent input-group-rounded"">
          <span class=""input-group-addon"">
            <i class=""fa fa-search""></i>
          </span>
          <input class=""form-control form-control-sm"" id=""table-search-input"" (keyup)=""filter($event)"" [(ngModel)]=""filterQuery"" type=""text"" placeholder=""Search by ");
            
            #line 24 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getSearchProperty()));
            
            #line default
            #line hidden
            this.Write(@"..."">
        </div>
      </div>
      <table class=""table table-striped table-hover"" [mfData]=""data"" #mf=""mfDataTable""
                   [mfRowsOnPage]=""rowsOnPage"" [(mfSortBy)]=""sortBy"" [(mfSortOrder)]=""sortOrder"" [mfActivePage]=""activePage""
                    (mfOnPageChange)=""onPageChange($event)"" [(mfAmountOfRows)]=""itemsTotal"" (mfSortOrderChange)=""onSortOrder($event)"">
        <thead>
        <tr>
		");
            
            #line 32 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
 foreach(PropertyInfo pi in listableProperties)
		{ 
            
            #line default
            #line hidden
            this.Write("          <th>\r\n            <mfDefaultSorter by=\"");
            
            #line 35 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pi.Name));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 35 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getNamedArgument<DisplayAttribute>(pi)));
            
            #line default
            #line hidden
            this.Write("</mfDefaultSorter>\r\n          </th>\r\n\t\t");
            
            #line 37 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("          <th class=\"no-sort\">\r\n            Action\r\n          </th>\r\n        </tr" +
                    ">\r\n        </thead>\r\n        <tbody>\r\n        <tr *ngFor=\"let ");
            
            #line 44 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name.ToLower(new System.Globalization.CultureInfo("en-EN", false))));
            
            #line default
            #line hidden
            this.Write(" of mf.data\">\r\n\t\t");
            
            #line 45 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
 foreach(PropertyInfo pi in listableProperties)
		{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t<td>{{");
            
            #line 47 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getListPropertyByType(pi)));
            
            #line default
            #line hidden
            this.Write("}}</td>\r\n\t\t");
            
            #line 48 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("          <td class=\"width-200\">\r\n            <a class=\"btn btn-secondary width-1" +
                    "00 mb-xs\" role=\"button\" [routerLink]=\"[\'/app/");
            
            #line 50 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(moduleName));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 50 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name.ToLower(new System.Globalization.CultureInfo("en-EN", false))));
            
            #line default
            #line hidden
            this.Write("\', ");
            
            #line 50 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name.ToLower(new System.Globalization.CultureInfo("en-EN", false))));
            
            #line default
            #line hidden
            this.Write(".Id]\">\r\n              <i class=\"glyphicon glyphicon-edit text-success\"></i>\r\n    " +
                    "          Edit\r\n            </a>\r\n            <button class=\"btn btn-secondary w" +
                    "idth-80 mb-xs\" role=\"button\" (click)=\"delete(");
            
            #line 54 "C:\Projects\focus\Generator\UIGenerator\Templates\ListHtmlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name.ToLower(new System.Globalization.CultureInfo("en-EN", false))));
            
            #line default
            #line hidden
            this.Write(@")"">
              <i class=""glyphicon glyphicon-trash text-danger""></i>
              Delete
            </button>
          </td>
        </tr>
        <tr *ngIf=""mf.data.length === 0"">
          <td colspan=""100"">
            Nothing found.
          </td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
          <td colspan=""12"">
            <mfBootstrapPaginator [rowsOnPageSet]=""[5, 10, 25]""></mfBootstrapPaginator>
          </td>
        </tr>
        </tfoot>
      </table>
    </div>
  </div>
</section>
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ListHtmlTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
