// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebApiGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class WebApiCsProjTemplate : WebApiCsProjTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<?xml version=""1.0"" encoding=""utf-8""?>
<Project ToolsVersion=""14.0"" DefaultTargets=""Build"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">
  <Import Project=""..\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props"" Condition=""Exists('..\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props')"" />
  <Import Project=""$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props"" Condition=""Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')"" />
  <PropertyGroup>
    <Configuration Condition="" '$(Configuration)' == '' "">Debug</Configuration>
    <Platform Condition="" '$(Platform)' == '' "">AnyCPU</Platform>
    <ProductVersion>
    </ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{1F81763F-DD4A-46A0-9D43-F99CEB5404F2}</ProjectGuid>
    <ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>");
            
            #line 20 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProjectName));
            
            #line default
            #line hidden
            this.Write("</RootNamespace>\r\n    <AssemblyName>");
            
            #line 21 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProjectName));
            
            #line default
            #line hidden
            this.Write("</AssemblyName>\r\n    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>\r\n    <" +
                    "MvcBuildViews>false</MvcBuildViews>\r\n    <UseIISExpress>true</UseIISExpress>\r\n  " +
                    "  <IISExpressSSLPort />\r\n    <IISExpressAnonymousAuthentication />\r\n    <IISExpr" +
                    "essWindowsAuthentication />\r\n    <IISExpressUseClassicPipelineMode />\r\n    <UseG" +
                    "lobalApplicationHostFile />\r\n    <NuGetPackageImportStamp>\r\n    </NuGetPackageIm" +
                    "portStamp>\r\n    <Use64BitIISExpress />\r\n  </PropertyGroup>\r\n  <PropertyGroup Con" +
                    "dition=\" \'$(Configuration)|$(Platform)\' == \'Debug|AnyCPU\' \">\r\n    <DebugSymbols>" +
                    "true</DebugSymbols>\r\n    <DebugType>full</DebugType>\r\n    <Optimize>false</Optim" +
                    "ize>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstants>DEBUG;TRACE</Defin" +
                    "eConstants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4</Warning" +
                    "Level>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\" \'$(Configuration)|$(Pla" +
                    "tform)\' == \'Release|AnyCPU\' \">\r\n    <DebugType>pdbonly</DebugType>\r\n    <Optimiz" +
                    "e>true</Optimize>\r\n    <OutputPath>bin\\</OutputPath>\r\n    <DefineConstants>TRACE" +
                    "</DefineConstants>\r\n    <ErrorReport>prompt</ErrorReport>\r\n    <WarningLevel>4</" +
                    "WarningLevel>\r\n  </PropertyGroup>\r\n  <ItemGroup>\r\n    <Reference Include=\"Autofa" +
                    "c, Version=4.6.2.0, Culture=neutral, PublicKeyToken=17863af14b0044da, processorA" +
                    "rchitecture=MSIL\">\r\n      <HintPath>..\\packages\\Autofac.4.6.2\\lib\\net45\\Autofac." +
                    "dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Autofac.Integration.We" +
                    "bApi, Version=4.1.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da, process" +
                    "orArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\Autofac.WebApi2.4.1.0\\lib\\net" +
                    "45\\Autofac.Integration.WebApi.dll</HintPath>\r\n      <Private>True</Private>\r\n   " +
                    " </Reference>\r\n    <Reference Include=\"Bogus, Version=25.0.1.0, Culture=neutral," +
                    " PublicKeyToken=fa1bb3f3f218129a, processorArchitecture=MSIL\">\r\n      <HintPath>" +
                    "..\\packages\\Bogus.25.0.1\\lib\\net40\\Bogus.dll</HintPath>\r\n    </Reference>\r\n    <" +
                    "Reference Include=\"EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyT" +
                    "oken=b77a5c561934e089, processorArchitecture=MSIL\">\r\n      <HintPath>..\\packages" +
                    "\\EntityFramework.6.2.0\\lib\\net45\\EntityFramework.dll</HintPath>\r\n    </Reference" +
                    ">\r\n    <Reference Include=\"EntityFramework.Extended, Version=6.0.0.0, Culture=ne" +
                    "utral, PublicKeyToken=05b7e29bdd433584, processorArchitecture=MSIL\">\r\n      <Hin" +
                    "tPath>..\\packages\\EntityFramework.Extended.6.1.0.168\\lib\\net45\\EntityFramework.E" +
                    "xtended.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n    <Re" +
                    "ference Include=\"EntityFramework.SqlServer, Version=6.0.0.0, Culture=neutral, Pu" +
                    "blicKeyToken=b77a5c561934e089, processorArchitecture=MSIL\">\r\n      <HintPath>..\\" +
                    "packages\\EntityFramework.6.2.0\\lib\\net45\\EntityFramework.SqlServer.dll</HintPath" +
                    ">\r\n    </Reference>\r\n    <Reference Include=\"Focus.Common, Version=1.0.0.0, Cult" +
                    "ure=neutral, processorArchitecture=MSIL\">\r\n      <SpecificVersion>False</Specifi" +
                    "cVersion>\r\n      <HintPath>..\\..\\..\\Focus.Common.dll</HintPath>\r\n    </Reference" +
                    ">\r\n    <Reference Include=\"Microsoft.CSharp\" />\r\n    <Reference Include=\"Microso" +
                    "ft.Owin, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, proc" +
                    "essorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\Microsoft.Owin.3.1.0\\lib\\n" +
                    "et45\\Microsoft.Owin.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Referen" +
                    "ce>\r\n    <Reference Include=\"Microsoft.Owin.Cors, Version=3.1.0.0, Culture=neutr" +
                    "al, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">\r\n      <HintPa" +
                    "th>..\\packages\\Microsoft.Owin.Cors.3.1.0\\lib\\net45\\Microsoft.Owin.Cors.dll</Hint" +
                    "Path>\r\n      <Private>True</Private>\r\n    </Reference>\r\n    <Reference Include=\"" +
                    "Microsoft.Owin.Security.Jwt\">\r\n      <HintPath>..\\packages\\Microsoft.Owin.Securi" +
                    "ty.Jwt.3.0.0\\lib\\net45\\Microsoft.Owin.Security.Jwt.dll</HintPath>\r\n    </Referen" +
                    "ce>\r\n    <Reference Include=\"Newtonsoft.Json, Version=11.0.0.0, Culture=neutral," +
                    " PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL\">\r\n      <HintPath>" +
                    "..\\packages\\Newtonsoft.Json.11.0.1\\lib\\net45\\Newtonsoft.Json.dll</HintPath>\r\n   " +
                    " </Reference>\r\n    <Reference Include=\"");
            
            #line 91 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProjectName));
            
            #line default
            #line hidden
            this.Write(".Common, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL\">\r\n      <S" +
                    "pecificVersion>False</SpecificVersion>\r\n      <HintPath>..\\Libraries\\");
            
            #line 93 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ProjectName));
            
            #line default
            #line hidden
            this.Write(".Common.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"SendGridMail\">\r" +
                    "\n      <HintPath>..\\packages\\Sendgrid.5.0.0\\lib\\SendGridMail.dll</HintPath>\r\n   " +
                    " </Reference>\r\n    <Reference Include=\"Serilog, Version=2.0.0.0, Culture=neutral" +
                    ", PublicKeyToken=24c2f752a8e58a10, processorArchitecture=MSIL\">\r\n      <HintPath" +
                    ">..\\packages\\Serilog.2.6.0\\lib\\net45\\Serilog.dll</HintPath>\r\n    </Reference>\r\n " +
                    "   <Reference Include=\"Serilog.Settings.AppSettings, Version=2.0.0.0, Culture=ne" +
                    "utral, PublicKeyToken=24c2f752a8e58a10, processorArchitecture=MSIL\">\r\n      <Hin" +
                    "tPath>..\\packages\\Serilog.Settings.AppSettings.2.1.2\\lib\\net45\\Serilog.Settings." +
                    "AppSettings.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Serilog.Si" +
                    "nks.Console, Version=3.0.1.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10, " +
                    "processorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\Serilog.Sinks.Console." +
                    "3.0.1\\lib\\net45\\Serilog.Sinks.Console.dll</HintPath>\r\n    </Reference>\r\n    <Ref" +
                    "erence Include=\"Serilog.Sinks.Literate, Version=3.0.0.0, Culture=neutral, Public" +
                    "KeyToken=24c2f752a8e58a10, processorArchitecture=MSIL\">\r\n      <HintPath>..\\pack" +
                    "ages\\Serilog.Sinks.Literate.3.0.0\\lib\\net45\\Serilog.Sinks.Literate.dll</HintPath" +
                    ">\r\n    </Reference>\r\n    <Reference Include=\"Serilog.Sinks.MSSqlServer, Version=" +
                    "5.1.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10, processorArchitecture" +
                    "=MSIL\">\r\n      <HintPath>..\\packages\\Serilog.Sinks.MSSqlServer.5.1.0\\lib\\net45\\S" +
                    "erilog.Sinks.MSSqlServer.dll</HintPath>\r\n    </Reference>\r\n    <Reference Includ" +
                    "e=\"Serilog.Sinks.PeriodicBatching, Version=2.0.0.0, Culture=neutral, PublicKeyTo" +
                    "ken=24c2f752a8e58a10, processorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\" +
                    "Serilog.Sinks.PeriodicBatching.2.1.1\\lib\\net45\\Serilog.Sinks.PeriodicBatching.dl" +
                    "l</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"System\" />\r\n    <Referen" +
                    "ce Include=\"System.Data\" />\r\n    <Reference Include=\"System.Drawing\" />\r\n    <Re" +
                    "ference Include=\"System.IdentityModel\" />\r\n    <Reference Include=\"System.Identi" +
                    "tyModel.Tokens.Jwt\">\r\n      <HintPath>..\\packages\\System.IdentityModel.Tokens.Jw" +
                    "t.4.0.1\\lib\\net45\\System.IdentityModel.Tokens.Jwt.dll</HintPath>\r\n    </Referenc" +
                    "e>\r\n    <Reference Include=\"System.IO.Compression.FileSystem\" />\r\n    <Reference" +
                    " Include=\"System.Numerics\" />\r\n    <Reference Include=\"System.Web.Cors, Version=" +
                    "5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture" +
                    "=MSIL\">\r\n      <HintPath>..\\packages\\Microsoft.AspNet.Cors.5.2.3\\lib\\net45\\Syste" +
                    "m.Web.Cors.dll</HintPath>\r\n      <Private>True</Private>\r\n    </Reference>\r\n    " +
                    "<Reference Include=\"System.Web.Entity\" />\r\n    <Reference Include=\"System.Web.Ap" +
                    "plicationServices\" />\r\n    <Reference Include=\"System.ComponentModel.DataAnnotat" +
                    "ions\" />\r\n    <Reference Include=\"System.Core\" />\r\n    <Reference Include=\"Syste" +
                    "m.Data.DataSetExtensions\" />\r\n    <Reference Include=\"System.Web.Http.Cors, Vers" +
                    "ion=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitec" +
                    "ture=MSIL\">\r\n      <HintPath>..\\packages\\Microsoft.AspNet.WebApi.Cors.5.2.3\\lib\\" +
                    "net45\\System.Web.Http.Cors.dll</HintPath>\r\n      <Private>True</Private>\r\n    </" +
                    "Reference>\r\n    <Reference Include=\"System.Xml.Linq\" />\r\n    <Reference Include=" +
                    "\"System.Web\" />\r\n    <Reference Include=\"System.Web.Abstractions\" />\r\n    <Refer" +
                    "ence Include=\"System.Web.Routing\" />\r\n    <Reference Include=\"System.Xml\" />\r\n  " +
                    "  <Reference Include=\"System.Configuration\" />\r\n    <Reference Include=\"System.R" +
                    "untime.Serialization\" />\r\n    <Reference Include=\"Microsoft.Web.Infrastructure, " +
                    "Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArch" +
                    "itecture=MSIL\">\r\n      <Private>True</Private>\r\n      <HintPath>..\\packages\\Micr" +
                    "osoft.Web.Infrastructure.1.0.0.0\\lib\\net40\\Microsoft.Web.Infrastructure.dll</Hin" +
                    "tPath>\r\n    </Reference>\r\n    <Reference Include=\"System.Net.Http\">\r\n    </Refer" +
                    "ence>\r\n    <Reference Include=\"System.Net.Http.Formatting, Version=5.2.3.0, Cult" +
                    "ure=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">\r\n    " +
                    "  <HintPath>..\\packages\\Microsoft.AspNet.WebApi.Client.5.2.3\\lib\\net45\\System.Ne" +
                    "t.Http.Formatting.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Syst" +
                    "em.Net.Http.WebRequest\">\r\n    </Reference>\r\n    <Reference Include=\"System.Web.H" +
                    "elpers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, proce" +
                    "ssorArchitecture=MSIL\">\r\n      <Private>True</Private>\r\n      <HintPath>..\\packa" +
                    "ges\\Microsoft.AspNet.WebPages.3.2.3\\lib\\net45\\System.Web.Helpers.dll</HintPath>\r" +
                    "\n    </Reference>\r\n    <Reference Include=\"System.Web.Http, Version=5.2.3.0, Cul" +
                    "ture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">\r\n   " +
                    "   <HintPath>..\\packages\\Microsoft.AspNet.WebApi.Core.5.2.3\\lib\\net45\\System.Web" +
                    ".Http.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"System.Web.Http." +
                    "WebHost, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, proc" +
                    "essorArchitecture=MSIL\">\r\n      <HintPath>..\\packages\\Microsoft.AspNet.WebApi.We" +
                    "bHost.5.2.3\\lib\\net45\\System.Web.Http.WebHost.dll</HintPath>\r\n    </Reference>\r\n" +
                    "    <Reference Include=\"System.Web.Mvc, Version=5.2.3.0, Culture=neutral, Public" +
                    "KeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">\r\n      <Private>True</Pr" +
                    "ivate>\r\n      <HintPath>..\\packages\\Microsoft.AspNet.Mvc.5.2.3\\lib\\net45\\System." +
                    "Web.Mvc.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"System.Web.Opt" +
                    "imization\">\r\n      <HintPath>..\\packages\\Microsoft.AspNet.Web.Optimization.1.1.3" +
                    "\\lib\\net40\\System.Web.Optimization.dll</HintPath>\r\n    </Reference>\r\n    <Refere" +
                    "nce Include=\"System.Web.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=" +
                    "31bf3856ad364e35, processorArchitecture=MSIL\">\r\n      <Private>True</Private>\r\n " +
                    "     <HintPath>..\\packages\\Microsoft.AspNet.Razor.3.2.3\\lib\\net45\\System.Web.Raz" +
                    "or.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"System.Web.WebPages" +
                    ", Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorAr" +
                    "chitecture=MSIL\">\r\n      <Private>True</Private>\r\n      <HintPath>..\\packages\\Mi" +
                    "crosoft.AspNet.WebPages.3.2.3\\lib\\net45\\System.Web.WebPages.dll</HintPath>\r\n    " +
                    "</Reference>\r\n    <Reference Include=\"System.Web.WebPages.Deployment, Version=3." +
                    "0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=M" +
                    "SIL\">\r\n      <Private>True</Private>\r\n      <HintPath>..\\packages\\Microsoft.AspN" +
                    "et.WebPages.3.2.3\\lib\\net45\\System.Web.WebPages.Deployment.dll</HintPath>\r\n    <" +
                    "/Reference>\r\n    <Reference Include=\"System.Web.WebPages.Razor, Version=3.0.0.0," +
                    " Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL\">\r" +
                    "\n      <Private>True</Private>\r\n      <HintPath>..\\packages\\Microsoft.AspNet.Web" +
                    "Pages.3.2.3\\lib\\net45\\System.Web.WebPages.Razor.dll</HintPath>\r\n    </Reference>" +
                    "\r\n    <Reference Include=\"Thinktecture.IdentityModel.Core\">\r\n      <HintPath>..\\" +
                    "packages\\Thinktecture.IdentityModel.Core.1.3.0\\lib\\net45\\Thinktecture.IdentityMo" +
                    "del.Core.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"WebGrease\">\r\n" +
                    "      <Private>True</Private>\r\n      <HintPath>..\\packages\\WebGrease.1.5.2\\lib\\W" +
                    "ebGrease.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Antlr3.Runtim" +
                    "e\">\r\n      <Private>True</Private>\r\n      <HintPath>..\\packages\\Antlr.3.4.1.9004" +
                    "\\lib\\Antlr3.Runtime.dll</HintPath>\r\n    </Reference>\r\n  </ItemGroup>\r\n  <ItemGro" +
                    "up>\r\n    <Reference Include=\"Microsoft.AspNet.Identity.Core\">\r\n      <HintPath>." +
                    ".\\packages\\Microsoft.AspNet.Identity.Core.2.2.1\\lib\\net45\\Microsoft.AspNet.Ident" +
                    "ity.Core.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Microsoft.Asp" +
                    "Net.Identity.Owin\">\r\n      <HintPath>..\\packages\\Microsoft.AspNet.Identity.Owin." +
                    "2.2.1\\lib\\net45\\Microsoft.AspNet.Identity.Owin.dll</HintPath>\r\n    </Reference>\r" +
                    "\n    <Reference Include=\"Microsoft.AspNet.Identity.EntityFramework\">\r\n      <Hin" +
                    "tPath>..\\packages\\Microsoft.AspNet.Identity.EntityFramework.2.2.1\\lib\\net45\\Micr" +
                    "osoft.AspNet.Identity.EntityFramework.dll</HintPath>\r\n    </Reference>\r\n    <Ref" +
                    "erence Include=\"Owin\">\r\n      <HintPath>..\\packages\\Owin.1.0\\lib\\net40\\Owin.dll<" +
                    "/HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Microsoft.Owin.Host.System" +
                    "Web\">\r\n      <HintPath>..\\packages\\Microsoft.Owin.Host.SystemWeb.3.0.1\\lib\\net45" +
                    "\\Microsoft.Owin.Host.SystemWeb.dll</HintPath>\r\n    </Reference>\r\n    <Reference " +
                    "Include=\"Microsoft.Owin.Security\">\r\n      <HintPath>..\\packages\\Microsoft.Owin.S" +
                    "ecurity.3.0.1\\lib\\net45\\Microsoft.Owin.Security.dll</HintPath>\r\n    </Reference>" +
                    "\r\n    <Reference Include=\"Microsoft.Owin.Security.Facebook\">\r\n      <HintPath>.." +
                    "\\packages\\Microsoft.Owin.Security.Facebook.3.0.1\\lib\\net45\\Microsoft.Owin.Securi" +
                    "ty.Facebook.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Microsoft." +
                    "Owin.Security.Cookies\">\r\n      <HintPath>..\\packages\\Microsoft.Owin.Security.Coo" +
                    "kies.3.0.1\\lib\\net45\\Microsoft.Owin.Security.Cookies.dll</HintPath>\r\n    </Refer" +
                    "ence>\r\n    <Reference Include=\"Microsoft.Owin.Security.OAuth\">\r\n      <HintPath>" +
                    "..\\packages\\Microsoft.Owin.Security.OAuth.3.0.1\\lib\\net45\\Microsoft.Owin.Securit" +
                    "y.OAuth.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Microsoft.Owin" +
                    ".Security.Google\">\r\n      <HintPath>..\\packages\\Microsoft.Owin.Security.Google.3" +
                    ".0.1\\lib\\net45\\Microsoft.Owin.Security.Google.dll</HintPath>\r\n    </Reference>\r\n" +
                    "    <Reference Include=\"Microsoft.Owin.Security.Twitter\">\r\n      <HintPath>..\\pa" +
                    "ckages\\Microsoft.Owin.Security.Twitter.3.0.1\\lib\\net45\\Microsoft.Owin.Security.T" +
                    "witter.dll</HintPath>\r\n    </Reference>\r\n    <Reference Include=\"Microsoft.Owin." +
                    "Security.MicrosoftAccount\">\r\n      <HintPath>..\\packages\\Microsoft.Owin.Security" +
                    ".MicrosoftAccount.3.0.1\\lib\\net45\\Microsoft.Owin.Security.MicrosoftAccount.dll</" +
                    "HintPath>\r\n    </Reference>\r\n    <Reference Include=\"System.Web.Http.Owin\">\r\n   " +
                    "   <HintPath>..\\packages\\Microsoft.AspNet.WebApi.Owin.5.2.3\\lib\\net45\\System.Web" +
                    ".Http.Owin.dll</HintPath>\r\n    </Reference>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    " +
                    "<Compile Include=\"App_Start\\BundleConfig.cs\" />\r\n    <Compile Include=\"App_Start" +
                    "\\FilterConfig.cs\" />\r\n    <Compile Include=\"App_Start\\IdentityConfig.cs\" />\r\n   " +
                    " <Compile Include=\"App_Start\\RouteConfig.cs\" />\r\n    <Compile Include=\"App_Start" +
                    "\\Startup.Auth.cs\" />\r\n    <Compile Include=\"App_Start\\WebApiConfig.cs\" />\r\n    <" +
                    "Compile Include=\"Controllers\\AccountController.cs\" />\r\n");
            
            #line 250 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
 for(int i=0; i<Modules.Count; i++)
{
var module = Modules[i];
for(int j=0; j<module.Models.Count; j++)
{
var type = module.Models[j];
if (type.BaseType != typeof(Enum))
{ 
            
            #line default
            #line hidden
            this.Write("    <Compile Include=\"Controllers\\");
            
            #line 258 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(module.ModuleName));
            
            #line default
            #line hidden
            this.Write("\\");
            
            #line 258 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Name));
            
            #line default
            #line hidden
            this.Write("Controller.cs\" />\r\n");
            
            #line 259 "C:\aurea-projects\focus\Generator\WebApiGenerator\Templates\WebApiCsProjTemplate.tt"
 }
}
} 
            
            #line default
            #line hidden
            this.Write("    <Compile Include=\"Controllers\\BaseController.cs\" />\r\n    <Compile Include=\"Fi" +
                    "lters\\ClaimsAuthorizationAttribute.cs\" />\r\n    <Compile Include=\"Filters\\CustomA" +
                    "uthorizeAttribute.cs\" />\r\n    <Compile Include=\"Filters\\LogActionFilter.cs\" />\r\n" +
                    "    <Compile Include=\"Filters\\LogExceptionFilterAttribute.cs\" />\r\n    <Compile I" +
                    "nclude=\"Filters\\UpdateFKAttribute.cs\" />\r\n    <Compile Include=\"Filters\\Validate" +
                    "ModelAttribute.cs\" />\r\n    <Compile Include=\"Global.asax.cs\">\r\n      <DependentU" +
                    "pon>Global.asax</DependentUpon>\r\n    </Compile>\r\n    <Compile Include=\"Helpers\\R" +
                    "eflectionExtensions.cs\" />\r\n    <Compile Include=\"Models\\AccountBindingModels.cs" +
                    "\" />\r\n    <Compile Include=\"Models\\AccountViewModels.cs\" />\r\n    <Compile Includ" +
                    "e=\"Models\\ApplicationRoleManager.cs\" />\r\n    <Compile Include=\"Models\\IdentityMo" +
                    "dels.cs\" />\r\n    <Compile Include=\"Models\\ModelFactory.cs\" />\r\n    <Compile Incl" +
                    "ude=\"Models\\Role.cs\" />\r\n    <Compile Include=\"Properties\\AssemblyInfo.cs\" />\r\n " +
                    "   <Compile Include=\"Providers\\CustomJwtFormat.cs\" />\r\n    <Compile Include=\"Pro" +
                    "viders\\CustomOAuthProvider.cs\" />\r\n    <Compile Include=\"Results\\ChallengeResult" +
                    ".cs\" />\r\n    <Compile Include=\"Services\\EmailService.cs\" />\r\n    <Compile Includ" +
                    "e=\"Startup.cs\" />\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <Content Include=\"Global.a" +
                    "sax\" />\r\n    <Content Include=\"Web.config\">\r\n      <SubType>Designer</SubType>\r\n" +
                    "    </Content>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <Content Include=\"packages.co" +
                    "nfig\" />\r\n  </ItemGroup>\r\n  <PropertyGroup>\r\n    <VisualStudioVersion Condition=" +
                    "\"\'$(VisualStudioVersion)\' == \'\'\">10.0</VisualStudioVersion>\r\n    <VSToolsPath Co" +
                    "ndition=\"\'$(VSToolsPath)\' == \'\'\">$(MSBuildExtensionsPath32)\\Microsoft\\VisualStud" +
                    "io\\v$(VisualStudioVersion)</VSToolsPath>\r\n  </PropertyGroup>\r\n  <Import Project=" +
                    "\"$(MSBuildBinPath)\\Microsoft.CSharp.targets\" />\r\n  <Import Project=\"$(VSToolsPat" +
                    "h)\\WebApplications\\Microsoft.WebApplication.targets\" Condition=\"\'$(VSToolsPath)\'" +
                    " != \'\'\" />\r\n  <Import Project=\"$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio" +
                    "\\v10.0\\WebApplications\\Microsoft.WebApplication.targets\" Condition=\"false\" />\r\n " +
                    " <Target Name=\"MvcBuildViews\" AfterTargets=\"AfterBuild\" Condition=\"\'$(MvcBuildVi" +
                    "ews)\'==\'true\'\">\r\n    <AspNetCompiler VirtualPath=\"temp\" PhysicalPath=\"$(WebProje" +
                    "ctOutputDir)\" />\r\n  </Target>\r\n  <ProjectExtensions>\r\n    <VisualStudio>\r\n      " +
                    "<FlavorProperties GUID=\"{349c5851-65df-11da-9384-00065b846f21}\">\r\n        <WebPr" +
                    "ojectProperties>\r\n          <UseIIS>True</UseIIS>\r\n          <AutoAssignPort>Tru" +
                    "e</AutoAssignPort>\r\n          <DevelopmentServerPort>62747</DevelopmentServerPor" +
                    "t>\r\n          <DevelopmentServerVPath>/</DevelopmentServerVPath>\r\n          <IIS" +
                    "Url>http://localhost:62747/</IISUrl>\r\n          <NTLMAuthentication>False</NTLMA" +
                    "uthentication>\r\n          <UseCustomServer>False</UseCustomServer>\r\n          <C" +
                    "ustomServerUrl>\r\n          </CustomServerUrl>\r\n          <SaveServerSettingsInUs" +
                    "erFile>False</SaveServerSettingsInUserFile>\r\n        </WebProjectProperties>\r\n  " +
                    "    </FlavorProperties>\r\n    </VisualStudio>\r\n  </ProjectExtensions>\r\n  <Target " +
                    "Name=\"EnsureNuGetPackageBuildImports\" BeforeTargets=\"PrepareForBuild\">\r\n    <Pro" +
                    "pertyGroup>\r\n      <ErrorText>This project references NuGet package(s) that are " +
                    "missing on this computer. Use NuGet Package Restore to download them.  For more " +
                    "information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file" +
                    " is {0}.</ErrorText>\r\n    </PropertyGroup>\r\n    <Error Condition=\"!Exists(\'..\\pa" +
                    "ckages\\Microsoft.Net.Compilers.1.0.0\\build\\Microsoft.Net.Compilers.props\')\" Text" +
                    "=\"$([System.String]::Format(\'$(ErrorText)\', \'..\\packages\\Microsoft.Net.Compilers" +
                    ".1.0.0\\build\\Microsoft.Net.Compilers.props\'))\" />\r\n  </Target>\r\n  <!-- To modify" +
                    " your build process, add your task inside one of the targets below and uncomment" +
                    " it.\r\n       Other similar extension points exist, see Microsoft.Common.targets." +
                    "\r\n  <Target Name=\"BeforeBuild\">\r\n  </Target>\r\n  <Target Name=\"AfterBuild\">\r\n  </" +
                    "Target> -->\r\n</Project>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class WebApiCsProjTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
